import merch1 from "../assets/merch/merch1.png";
import merch2 from "../assets/merch/merch2.png";
import merch3 from "../assets/merch/merch3.png";
import merch4 from "../assets/merch/merch4.png";
import merch5 from "../assets/merch/merch5.png";
import merch6 from "../assets/merch/merch6.png";
import merch7 from "../assets/merch/merch7.png";
import merch8 from "../assets/merch/merch8.png";
import merch9 from "../assets/merch/merch9.png";

export const products = [
  {
    id: 1,
    name: '"Stay Fishy" T-Shirt',
    price: "NGN 20,000",
    image: merch1,
    colours: ["#E5E7EB", "#111827", "#6B7280"],
    material: "100% cotton",
    rating: 4.8,
    reviews: 120,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 2,
    name: '"Stay Fishy" T-Shirt',
    price: "NGN 20,000",
    image: merch2,
    colours: ["#111827", "#374151", "#E5E7EB"],
    material: "100% cotton",
    rating: 4.7,
    reviews: 98,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 3,
    name: '"Stay Fishy" T-Shirt',
    price: "NGN 20,000",
    image: merch3,
    colours: ["#F3F4F6", "#111827", "#9CA3AF"],
    material: "100% cotton",
    rating: 4.9,
    reviews: 167,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 4,
    name: '"Stay Fishy" Tank Top',
    price: "NGN 20,000",
    image: merch2,
    colours: ["#374151", "#111827", "#E5E7EB"],
    material: "100% cotton",
    rating: 4.6,
    reviews: 76,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 5,
    name: '"Stay Fishy" Tank Top',
    price: "NGN 20,000",
    image: merch4,
    colours: ["#6B7280", "#111827", "#E5E7EB"],
    material: "100% cotton",
    rating: 4.7,
    reviews: 63,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 6,
    name: '"Stay Fishy" Tank Top',
    price: "NGN 20,000",
    image: merch5,
    colours: ["#F3F4F6", "#111827", "#6B7280"],
    material: "100% cotton",
    rating: 4.5,
    reviews: 41,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 7,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch6,
    colours: ["#F3F4F6", "#111827", "#6B7280"],
    material: "Canvas",
    rating: 4.8,
    reviews: 54,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 8,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch7,
    colours: ["#111827", "#6B7280", "#F3F4F6"],
    material: "Canvas",
    rating: 4.7,
    reviews: 38,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 9,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch8,
    colours: ["#6B7280", "#111827", "#F3F4F6"],
    material: "Canvas",
    rating: 4.6,
    reviews: 29,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 10,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch9,
    colours: ["#F3F4F6", "#6B7280", "#111827"],
    material: "Canvas",
    rating: 4.9,
    reviews: 72,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 11,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch7,
    colours: ["#111827", "#6B7280", "#F3F4F6"],
    material: "Canvas",
    rating: 4.8,
    reviews: 44,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
  {
    id: 12,
    name: '"Stay Fishy" Tote Bag',
    price: "NGN 10,000",
    image: merch6,
    colours: ["#F3F4F6", "#111827", "#6B7280"],
    material: "Canvas",
    rating: 4.7,
    reviews: 31,
    warrantyMonths: 6,
    deliveryLabel: "Free Delivery",
  },
];
